services:
  nginx:
    image: nginx:latest
    volumes:
      - ./windows.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_logs:/var/log/nginx
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
